---
title: "Homework 1"
output:
  html_document: 
    toc: true
    toc_float: true
---

### Context

This assignment reinforces ideas in the [building blocks](topic_building_blocks.html) topic. 

### Due date and submission.

Due: September 21 at 4:00pm. 

Please submit (via courseworks) the web address of the GitHub repo containing your work for this assignment; git commits after the due date will cause the assignment to be considered late.

### Points

* Problem 0.1: 25 points
* Problem 0.2: 25 points
* Problem 1: 25 points
* Problem 2: 25 points
* Problem 3: added late, no points


### Problem 0.1

This "problem" focuses on the use of R Markdown to write reproducible reports, GitHub for version control, and R Projects to organize your work.

To that end: 

* create a public GitHub repo + local R Project; we suggest naming this repo / directory `p8105_hw1_YOURUNI` (e.g. `p8105_hw1_ajg2202` for Jeff), but that's not required
* create a single .Rmd file named `p8105_hw1_YOURUNI.Rmd` that renders to `github_document`
* submit a link to your repo via Courseworks

Your solutions to Problems 1 and 2 should be implemented in your .Rmd file, and your git commit history should reflect the process you used to solve these Problems. 

For this Problem, we will assess adherence to the instructions above regarding repo structure, git commit history, and whether we are able to knit your .Rmd to ensure that your work is reproducible. 


### Problem 0.2

This "problem" focuses on correct styling for your solutions to Problems 1 and 2. We will look for:

* meaningful variable / object names
* readable code (one command per line; adequate whitespace and indentation; etc)
* clearly-written text to explain code and results 
* a lack of superfluous code (e.g. no unused variables are defined)


### Problem 1

This problem focuses on variable types and coercion.

Create a data frame comprised of:

* A random sample of size 10 from a uniform[0, 5] distribution
* A logical vector indicating whether elements of the sample are greater than 2
* A (length-10) character vector
* A (length-10) factor vector
  
Try to take the mean of each variable in your dataframe. What works and what doesn't? Why?

In some cases, you can explicitly convert variables from one type to another. Write a code chunk that applies the `as.numeric` function to the logical, character, and factor variables (please show this chunk but not the output). What happens? In a second code chunk, convert your character variable from character to factor to numeric; similarly, convert your factor variable from factor to character to numeric. What happens?


### Problem 2

This problem focuses on plotting and the use of inline R code.

* Create a data frame comprised of:
    * `x`: a random sample of size 1000 from a standard Normal distribution
    * `y`: a random sample of size 1000 from a standard Normal distribution
    * A logical vector indicating whether the `x + y > 0`
    * A numeric vector created by coercing the above logical vector
    * A factor vector created by coercing the above logical vector

Write a short description of your vector using inline R code, including:
* the size of the dataset
* the mean and median of `x`
* the proportion of cases for which the logical vector is `TRUE`

Make a scatterplot of `y` vs `x`; color points using the logical variable (adding `color = ...` inside of `aes` in your ggplot code should help). Make a second and third scatterplot that color points using the numeric and factor variables, respectively, and comment on the color scales.

Export your first scatterplot to your project directory using `ggsave`. 


### Problem 3 

Please complete [this google form](https://docs.google.com/forms/d/e/1FAIpQLSfjuJzeKUHshu9_S6tr9PiRgrPXFMBMo284fI7WH3MechaUMw/viewform?usp=sf_link).