---
title: "Schedule"
---

| Date          | Topic                 | Lecture                                                       | Slides                                                                        |  Slack                                          | HW                                                         |                        Projects |
|:------------- |:--------------------- |:--------------------------------------------------------------|:-----------------------------------------------------------------------------:|:-----------------------------------------------:|:----------------------------------------------------------:| -------------------------------:|
| Tues Sept 4   | What is Data Science? | [What is Data Science?](what_is_ds_i.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_i.pdf)     | [<i class="fab fa-slack fa-lg"></i>](link)      | [<i class="far fa-file-code fa-lg"></i>](homework_0.html)  |                                 |   
| Thur Sept 6   | Building blocks       | [Best Practices](best_practices.html)                         | [<i class="fas fa-desktop fa-lg"></i>](slides/best_practices.pdf)             | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCATLJG67)      |                                                            |                                 |
| Tues Sept 11  | Building blocks       | [Writing with Data](writing_with_data.html)                   | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_with_data.pdf)          | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCATLJG67)      |                                                            |                                 |
| Thur Sept 13  | Building blocks       | [Git](git.html)                                               | [<i class="fas fa-desktop fa-lg"></i>](slides/git.pdf)                        | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCATLJG67)      | [<i class="far fa-file-code fa-lg"></i>](homework_1.html)  |                                 |   
| Tues Sept 18  | Data Wrangling I      | [Data Import](data_import.html)                               | [<i class="fas fa-desktop fa-lg"></i>](slides/data_import.pdf)                | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCAEZLU49)      |                                                            |                                 |
| Thur Sept 20  | Data Wrangling I      | [Data Manipulation](data_manipulation.html)                   | [<i class="fas fa-desktop fa-lg"></i>](slides/data_manipulation.pdf)          | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCAEZLU49)      |                                                            |                                 |
| Tues Sept 25  | Data Wrangling I      | [Tidy data](tidy_data.html)                                   | [<i class="fas fa-desktop fa-lg"></i>](slides/tidy_data.pdf)                  | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCAEZLU49)      | [<i class="far fa-file-code fa-lg"></i>](homework_2.html)  |                                 |   
| Thur Sept 27  | Viz + EDA             | [Visualization 1](visualization_pt1.html)                     | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)              | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCCBZPUVC)      |                                                            |                                 |
| Tues Oct 2    | Viz + EDA             | [Visualization 2](visualization_pt2.html)                     | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)              | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCCBZPUVC)      |                                                            |                                 |
| Thur Oct 4    | Viz + EDA             | [EDA](exploratory_analysis.html)                              | [<i class="fas fa-desktop fa-lg"></i>](slides/exploratory_analysis.pdf)       | [<i class="fab fa-slack fa-lg"></i>](https://p8105-fall2018.slack.com/messages/CCCBZPUVC)      | [<i class="far fa-file-code fa-lg"></i>](homework_3.html)  |                                 |   
| Tues Oct 9    | Case Study            |                                                               | [<i class="fas fa-desktop fa-lg"></i>](link)                                  | [<i class="fab fa-slack fa-lg"></i>](link)      |                                                            |                                 |
| Thur Oct 11   | Data Wrangling II     | [Reading Data from the Web](reading_data_from_the_web.html)   | [<i class="fas fa-desktop fa-lg"></i>](slides/reading_data_from_the_web.pdf)  | [<i class="fab fa-slack fa-lg"></i>](link)      |                                                            |                                 |
| Tues Oct 16   | Data Wrangling II     | [Strings and Factors](strings_and_factors.html)               | [<i class="fas fa-desktop fa-lg"></i>](slides/strings_and_factors.pdf)        | [<i class="fab fa-slack fa-lg"></i>](link)      |                                                            | [Midterm](midterm_project.html) |
| Thur Oct 18   | Interactivity         | [Plot.ly and Dashboards](plotly_and_dashboards.html)          | [<i class="fas fa-desktop fa-lg"></i>](slides/plotly_and_dashboards.pdf)      | [<i class="fab fa-slack fa-lg"></i>](link)      |                                                            |                                 |
| Tues Oct 23   | Interactivity         | [Making Websites](making_websites.html)                       | [<i class="fas fa-desktop fa-lg"></i>](slides/making_websites.pdf)            | [<i class="fab fa-slack fa-lg"></i>](link)      | [<i class="far fa-file-code fa-lg"></i>](homework_4.html)  | [Final](final_project.html)     |
| Thur Oct 25   | Resampling            | [Writing Functions](writing_functions.html)                   | [<i class="fas fa-desktop fa-lg"></i>](link)                                  | [<i class="fab fa-slack fa-lg"></i>](link)      |                                                            |                                 |
| Tues Oct 30   | Resampling            | [Iteration and Simulation](iteration_and_simulation.html)     | [<i class="fas fa-desktop fa-lg"></i>](slides/iteration_and_simulation.pdf)   | [<i class="fab fa-slack fa-lg"></i>](link)      |                                                            |                                 |
| Thur Nov 1    | Resampling            | [listcols and Bootstrapping](listcols_and_bootstrapping.html) | [<i class="fas fa-desktop fa-lg"></i>](slides/listcols_and_bootstrapping.pdf) | [<i class="fab fa-slack fa-lg"></i>](link)      | [<i class="far fa-file-code fa-lg"></i>](homework_5.html)  |                                 |
| Tues Nov 6    | -Election day-        |                                                               |                                                                               |                                                 |                                                            |                                 |
| Thur Nov 8    | Linear models         |         | [<i class="fas fa-desktop fa-lg"></i>](link)  | [<i class="fab fa-slack fa-lg"></i>](link)      |      |     |
| Tues Nov 13   | Linear models         |         | [<i class="fas fa-desktop fa-lg"></i>](link)  | [<i class="fab fa-slack fa-lg"></i>](link)      |      |    |
| Thur Nov 15   | Linear models         |         | [<i class="fas fa-desktop fa-lg"></i>](link)  | [<i class="fab fa-slack fa-lg"></i>](link)      | [<i class="far fa-file-code fa-lg"></i>](homework_6.html)  |    |
| Tues Nov 20   | -Thanksgiving-        |         |                                               |                                                 |      |     |
| Thur Nov 22   | -Thanksgiving-        |         |                                               |                                                 |      |     |
| Tues Nov 27   | Extra topics          |         | [<i class="fas fa-desktop fa-lg"></i>](link)  | [<i class="fab fa-slack fa-lg"></i>](link)      |      |     |
| Thur Nov 29   | Extra topics          |         | [<i class="fas fa-desktop fa-lg"></i>](link)  | [<i class="fab fa-slack fa-lg"></i>](link)      | [<i class="far fa-file-code fa-lg"></i>](homework_7.html)  |    |
| Tues Dec 4    | -Final Project Week-  |         |                                               |                                                 |      |    |
| Thur Dec 6    | -Final Project Week-  |         |                                               |                                                 |      |     |
| Tues Dec 11   | Final Projects!  |         |                                               |                                                 |      |     |

